### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by EduardSergeev**
Just a simple github action which builds and tests the project.

~PS The tests [are broken](https://github.com/EduardSergeev/haskell-raytracer/runs/1102164233#step:4:340) at the moment :)~ [fixed](https://github.com/EduardSergeev/haskell-raytracer/runs/1103494672)

### CODE REVIEW

**Comment by dmitryrotay** [comment]
Yeah I broke tests yesterday while refactoring didn't notice. I was just thinking about setting up CI and completely forgot about github actions, was going to go with Travis. Thanks for that! :)

**Comment by EduardSergeev** [comment]
Hmm, strange, the action seems [to stuck](https://github.com/dmitryrotay/haskell-raytracer/runs/1104037614) for some reason...
Yes, I'm using Travis in my projects, but last week I did some work for a project which is using github actions and I liked it :) They have very impressive [list of things](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) installed in the environment and also provide Linux, Windows & Mac.
I also tried to add coverage report to the build, but `stack test --coverage` seems to be broken in the latest Stack v2.3.3 :( (it's [fixed](https://github.com/commercialhaskell/stack/pull/5355) already, but somehow didn't make into the latest release).

**Comment by EduardSergeev** [comment]
By the way, regarding related subject of CI systems like TeamCity and Docker: you may already know about it but for me it was like a revelation: [Docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/). Such a cool feature which can (and probably should) be used instead of TeamCity for many projects.  
If you are not familiar with it: basically you create a Dockerfile which internally declares two (or more if needed) images:
1. Build image: something which is used to build your app. I.g. [.NET Core SDK](https://hub.docker.com/_/microsoft-dotnet-core-sdk/) plus anything you need to build your app with. This image can be big (SDK 3.1 is 708MB) but it doesn't matter because it's used only to build your binaries, pack your fronend with webpack etc. You can also run tests and stuff - it's your build environment. This image is getting built first.
1. Runtime image: you can use very small base image for it, like [mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine](https://hub.docker.com/_/microsoft-dotnet-core-aspnet/) which is only 105MB ([Alpine images](https://hub.docker.com/_/alpine?tab=tags) are the smallest base Linux images: only ~2MB). You then __copy all required build artefacts__ from the build image, maybe add anything else you need for runtime and that's it: you now have very small image with only necessary files.

I just used this approach to build images for Nuxt.js project and I loved it! Basically you just need a machine with only Docker installed: no more missing dependencies or wrong versions of some libraries installed on "build machine". Then you just delete the intermediate image and that's it: your machine is clean again. All build configuration is obviously stored in git (since it's just a Dockerfile). And with Github actions you can do it on Github machine.

Sorry for long rant, but I just amused by this technology, wanted to share :)

**Comment by dmitryrotay** [comment]
Yes! I think I've stumbled upon it while watching the k8s course. Super cool! Even if you actually need TeamCity or another CI tool, no more "I need to update my agents images now" annoyance. Amazing stuff, can't get over the feeling that many devs had this stuff figured out for a while. Well, better late than never I guess. :)

**Pull request merged**
